domain_to_newsSource = {
    # International News Sources
    "www.bbc.com": "BBC News",
    "www.cnn.com": "CNN",
    "www.theguardian.com": "The Guardian",
    "www.foxnews.com": "Fox News",
    "www.aljazeera.com": "Al Jazeera",
    "www.reuters.com": "Reuters",
    "www.nbcnews.com": "NBC News",
    "www.cbsnews.com": "CBS News",
    "www.abcnews.go.com": "ABC News",
    "www.apnews.com": "Associated Press",
    "www.npr.org": "NPR",
    "www.voanews.com": "Voice of America",
    "www.usatoday.com": "USA Today",
    "www.time.com": "Time Magazine",
    "www.politico.com": "Politico",
    "www.dw.com": "Deutsche Welle",
    "www.japantimes.co.jp": "The Japan Times",
    "www.hindustantimes.com": "Hindustan Times",
    "www.thehindu.com": "The Hindu",
    "www.indiatoday.in": "India Today",
    "www.globaltimes.cn": "Global Times",

    # Singaporean News Sources
    "www.straitstimes.com": "The Straits Times",
    "www.channelnewsasia.com": "Channel News Asia (CNA)",
    "www.todayonline.com": "TODAY Online",
    "www.zaobao.com.sg": "Lianhe Zaobao",
    "www.businesstimes.com.sg": "The Business Times",
    "www.mediacorp.sg": "Mediacorp",
    "www.mustsharenews.com": "Must Share News",
    "www.theonlinecitizen.com": "The Online Citizen",
    "www.mothership.sg": "Mothership",
    "www.asiaone.com": "AsiaOne",
    "www.redsports.sg": "Red Sports",
    "www.tnp.sg": "The New Paper",
    "www.ricemedia.co": "Rice Media",
    "www.singaporeuncensored.com": "Singapore Uncensored",
    "www.hardwarezone.com.sg": "HardwareZone",
    "www.theindependent.sg": "The Independent Singapore",
}
